language: python
sudo: false
python:
 - "3.5"
env:
 - DJANGO_VERSION=2.0
install:
 - pip install Django
 - pip install coverage
 - pip install python-coveralls
 - pip install -q -e .
script:
 - coverage run --source='url_health' manage.py test url_health
after_success:
  - coveralls